/*
 * Structure 4: Outputs, elementary flows for water, air and sludge (g/d)
 * They are pointers to variables from the object "Variables" (array)
 */
var Outputs={
  "COD":{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Chemical Oxygen Demand"  },
  "CO2":{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Carbon Dioxide"          },
  "CH4":{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Methane"                 },
  "TKN":{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Total Kjeldahl Nitrogen" },
  "NOx":{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Nitrate/Nitrite"         },
  "N2" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Nitrogen gas"            },
  "N2O":{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Nitrous oxide"           },
  "TP" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Total Phosphorus"        },
  "TS" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Total Sulfur"            },

  //metals
  "Ag" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Silver"    },
  "Al" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Aluminium" },
  "As" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Arsenic"   },
  "B"  :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Boron"     },
  "Ba" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Barium"    },
  "Be" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Berilium"  },
  "Br" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Bromine"   },
  "Ca" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Calcium"   },
  "Cd" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Cadmium"   },
  "Cl" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Chlorine"  },
  "Co" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Cobalt"    },
  "Cr" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Chromium"  },
  "Cu" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Copper"    },
  "F"  :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Fluorine"  },
  "Fe" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Iron"      },
  "Hg" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Mercury"   },
  "I"  :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Iodine"    },
  "K"  :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Potassium" },
  "Mg" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Magnesium" },
  "Mn" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Manganese" },
  "Mo" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Molybdenum"},
  "Na" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Sodium"    },
  "Ni" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Nickel"    },
  "Pb" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Lead"      },
  "Sb" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Antimony"  },
  "Sc" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Scandium"  },
  "Se" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Selenium"  },
  "Si" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Silicon"   },
  "Sn" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Tin"       },
  "Sr" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Strontium" },
  "Ti" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Titanium"  },
  "Tl" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Thallium"  },
  "V"  :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Vanadium"  },
  "W"  :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Tungsten"  },
  "Zn" :{influent:0, effluent:{water:0, air:0, sludge:0}, descr:"Effluent Zinc"      },
};
