var Terms={
	"BOD":{       unit:"g/m3", descr:"Total 5d biochemical oxygen demand"},
	"sBOD":{      unit:"g/m3", descr:"Soluble BOD"},
	"UBOD":{      unit:"g/m3", descr:"Ultimate biochemical oxygen demand"},
	"COD":{       unit:"g/m3", descr:"Total chemical oxygen demand"},
	"bCOD":{      unit:"g/m3", descr:"Biodegradable COD"},
	"pCOD":{      unit:"g/m3", descr:"Particulate COD"},
	"sCOD":{      unit:"g/m3", descr:"Soluble COD"},
	"nbCOD":{     unit:"g/m3", descr:"Nonbiodegradable COD"},
	"rbCOD":{     unit:"g/m3", descr:"Readily biodegradable COD"},
	"bsCOD":{     unit:"g/m3", descr:"Biodegradable soluble COD"},
	"b_col_COD":{ unit:"g/m3", descr:"Biodegradable colloidal COD"},
	"sbCOD":{     unit:"g/m3", descr:"Slowly biodegradable COD"},
	"bpCOD":{     unit:"g/m3", descr:"Biodegradable particulate COD"},
	"nbpCOD":{    unit:"g/m3", descr:"Nonbiodegradable particulate COD"},
	"nbsCOD":{    unit:"g/m3", descr:"Nonbiodegradable soluble COD"},
	"TKN":{       unit:"g/m3", descr:"Total Kjedahl nitrogen"},
	"bTKN":{      unit:"g/m3", descr:"Biodegradable TKN"},
	"sTKN":{      unit:"g/m3", descr:"Soluble TKN"},
	"ON":{        unit:"g/m3", descr:"Organic N"},
	"NH4-N":{     unit:"g/m3", descr:"Ammonia N"},
	"bON":{       unit:"g/m3", descr:"Biodegradable ON"},
	"nbON":{      unit:"g/m3", descr:"Nonbiodegradable ON"},
	"pON":{       unit:"g/m3", descr:"Particulate ON"},
	"bpON":{      unit:"g/m3", descr:"Biodegradable particulate ON"},
	"nbpON":{     unit:"g/m3", descr:"Nonbiodegradable particulate ON"},
	"sON":{       unit:"g/m3", descr:"Soluble ON"},
	"bsON":{      unit:"g/m3", descr:"Biodegradable soluble ON"},
	"nbsON":{     unit:"g/m3", descr:"Nonbiodegradable soluble ON"},
	"TP":{        unit:"g/m3", descr:"Total P"},
	"PO4":{       unit:"g/m3", descr:"Orthophosphate"},
  "OP":{        unit:"g/m3", descr:"Organic P"},
	"bpOP":{      unit:"g/m3", descr:"Biodegradable particulate organic P"},
	"nbpOP":{     unit:"g/m3", descr:"Nonbiodegradable particulate organic P"},
	"bsOP":{      unit:"g/m3", descr:"Biodegradable soluble organic P"},
	"nbsOP":{     unit:"g/m3", descr:"Nonbiodegradable soluble organic P"},
	"TSS":{       unit:"g/m3", descr:"Total suspended solids"},
	"VSS":{       unit:"g/m3", descr:"Volatile suspended solids"},
	"nbVSS":{     unit:"g/m3", descr:"Nonbiodegradable volatile suspended solids"},
	"iTSS":{      unit:"g/m3", descr:"Inert total suspended solids"},
}
