var Terms={
	"BOD":{       unit:"g/m3", descr:"Total 5d biochemical oxygen demand"},
	"sBOD":{      unit:"g/m3", descr:"Soluble BOD"},
	"UBOD":{      unit:"g/m3", descr:"Ultimate biochemical oxygen demand"},
	"COD":{       unit:"g/m3", descr:"Total chemical oxygen demand"},
	"bCOD":{      unit:"g/m3", descr:"Biodegradable COD"},
	"pCOD":{      unit:"g/m3", descr:"Particulate COD"},
	"sCOD":{      unit:"g/m3", descr:"Soluble COD"},
	"nbCOD":{     unit:"g/m3", descr:"Nonbiodegradable COD"},
	"rbCOD":{     unit:"g/m3", descr:"Readily biodegradable COD"},
	"bsCOD":{     unit:"g/m3", descr:"Biodegradable soluble COD"},
	"b_col_COD":{ unit:"g/m3", descr:"Biodegradable colloidal COD"},
	"sbCOD":{     unit:"g/m3", descr:"Slowly biodegradable COD"},
	"bpCOD":{     unit:"g/m3", descr:"Biodegradable particulate COD"},
	"nbpCOD":{    unit:"g/m3", descr:"Nonbiodegradable particulate COD"},
	"nbsCOD":{    unit:"g/m3", descr:"Nonbiodegradable soluble COD"},
	"TKN":{       unit:"g/m3", descr:"Total Kjedahl nitrogen"},
	"bTKN":{      unit:"g/m3", descr:"Biodegradable TKN"},
	"sTKN":{      unit:"g/m3", descr:"Soluble TKN"},
	"ON":{        unit:"g/m3", descr:"Organic N"},
	"NH4-N":{     unit:"g/m3", descr:"Ammonia N"},
	"bON":{       unit:"g/m3", descr:"Biodegradable ON"},
	"nbON":{      unit:"g/m3", descr:"Nonbiodegradable ON"},
	"pON":{       unit:"g/m3", descr:"Particulate ON"},
	"bpON":{      unit:"g/m3", descr:"Biodegradable particulate ON"},
	"nbpON":{     unit:"g/m3", descr:"Nonbiodegradable particulate ON"},
	"sON":{       unit:"g/m3", descr:"Soluble ON"},
	"bsON":{      unit:"g/m3", descr:"Biodegradable soluble ON"},
	"nbsON":{     unit:"g/m3", descr:"Nonbiodegradable soluble ON"},
	"TP":{        unit:"g/m3", descr:"Total P"},
	"PO4":{       unit:"g/m3", descr:"Orthphosphate"},
	"bpP":{       unit:"g/m3", descr:"Biodegradable particulate P"},
	"nbpP":{      unit:"g/m3", descr:"Nonbiodegradable particulate P"},
	"bsP":{       unit:"g/m3", descr:"Biodegradable soluble P"},
	"nbsP":{      unit:"g/m3", descr:"Nonbiodegradable soluble P"},
	"TSS":{       unit:"g/m3", descr:"Total suspended solids"},
	"VSS":{       unit:"g/m3", descr:"Volatile suspended solids"},
	"nbVSS":{     unit:"g/m3", descr:"Nonbiodegradable volatile suspended solids"},
	"iTSS":{      unit:"g/m3", descr:"Inert total suspended solids"},

//bod removal
bCOD:{                                    unit:"",  descr:""},
nbCOD:{                                   unit:"",  descr:""},
nbsCODe:{                                 unit:"",  descr:""},
nbpCOD:{                                  unit:"",  descr:""},
VSS_COD:{                                 unit:"",  descr:""},
nbVSS:{                                   unit:"",  descr:""},
iTSS:{                                    unit:"",  descr:""},
mu_mT:{                                   unit:"",  descr:""},
bHT:{                                     unit:"",  descr:""},
S:{                                       unit:"",  descr:""},
P_X_bio:{                                 unit:"",  descr:""},
P_X_VSS:{                                 unit:"",  descr:""},
P_X_TSS:{                                 unit:"",  descr:""},
X_VSS_V:{                                 unit:"",  descr:""},
X_TSS_V:{                                 unit:"",  descr:""},
V:{                                       unit:"",  descr:""},
tau:{                                     unit:"",  descr:""},
MLVSS:{                                   unit:"",  descr:""},
FM:{                                      unit:"",  descr:""},
BOD_loading:{                             unit:"",  descr:""},
bCOD_removed:{                            unit:"",  descr:""},
Y_obs_TSS:{                               unit:"",  descr:""},
Y_obs_VSS:{                               unit:"",  descr:""},
C_T:{                                     unit:"",  descr:""},
Pb:{                                      unit:"",  descr:""},
C_inf_20:{                                unit:"",  descr:""},
OTRf:{                                    unit:"",  descr:""},
SOTR:{                                    unit:"",  descr:""},
kg_O2_per_m3_air:{                        unit:"",  descr:""},
air_flowrate:{                            unit:"",  descr:""},

//nitrification
bCOD:{                                    unit:"",  descr:""},
nbCOD:{                                   unit:"",  descr:""},
nbsCODe:{                                 unit:"",  descr:""},
nbpCOD:{                                  unit:"",  descr:""},
VSS_COD:{                                 unit:"",  descr:""},
nbVSS:{                                   unit:"",  descr:""},
mu_max_AOB_T:{                            unit:"",  descr:""},
b_AOB_T:{                                 unit:"",  descr:""},
mu_AOB:{                                  unit:"",  descr:""},
SRT_theoretical:{                         unit:"",  descr:""},
SRT_design:{                              unit:"",  descr:""},
bHT:{                                     unit:"",  descr:""},
mu_mT:{                                   unit:"",  descr:""},
S:{                                       unit:"",  descr:""},
P_X_bio_VSS:{                             unit:"",  descr:""},
NOx:{                                     unit:"",  descr:""},
P_X_VSS:{                                 unit:"",  descr:""},
P_X_TSS:{                                 unit:"",  descr:""},
X_VSS_V:{                                 unit:"",  descr:""},
X_TSS_V:{                                 unit:"",  descr:""},
V:{                                       unit:"",  descr:""},
tau:{                                     unit:"",  descr:""},
MLVSS:{                                   unit:"",  descr:""},
FM:{                                      unit:"",  descr:""},
BOD_loading:{                             unit:"",  descr:""},
bCOD_removed:{                            unit:"",  descr:""},
Y_obs_TSS:{                               unit:"",  descr:""},
Y_obs_VSS:{                               unit:"",  descr:""},
P_X_bio_VSS_without_nitrifying:{          unit:"",  descr:""},
OTRf:{                                    unit:"",  descr:""},
C_inf_20:{                                unit:"",  descr:""},
Pb:{                                      unit:"",  descr:""},
SOTR:{                                    unit:"",  descr:""},
kg_O2_per_m3_air:{                        unit:"",  descr:""},
air_flowrate:{                            unit:"",  descr:""},
alkalinity_to_be_added:{                  unit:"",  descr:""},
BOD_eff:{                                 unit:"",  descr:""},

//sst                                     sizing
RAS:{                                     unit:"",  descr:""},
Area:{                                    unit:"",  descr:""},
area_per_clarifier:{                      unit:"",  descr:""},
clarifier_diameter:{                      unit:"",  descr:""},
Solids_loading:{                          unit:"",  descr:""},

//desnitrification
Xb:{                                      unit:"",  descr:""},
IR:{                                      unit:"",  descr:""},
Flowrate_to_anoxic_tank:{                 unit:"",  descr:""},
NOx_feed:{                                unit:"",  descr:""},
tau:{                                     unit:"",  descr:""},
V_nox:{                                   unit:"",  descr:""},
FM_b:{                                    unit:"",  descr:""},
Fraction_of_rbCOD:{                       unit:"",  descr:""},
b0:{                                      unit:"",  descr:""},
b1:{                                      unit:"",  descr:""},
SDNR_b:{                                  unit:"",  descr:""},
SDNR_T:{                                  unit:"",  descr:""},
SDNR_adj:{                                unit:"",  descr:""},
SDNR:{                                    unit:"",  descr:""},
NO_r:{                                    unit:"",  descr:""},
Net_O2_required:{                         unit:"",  descr:""},
Mass_of_alkalinity_needed:{               unit:"",  descr:""},
Power:{                                   unit:"",  descr:""},

//bioP
Q_rbCOD:{                                 unit:"",  descr:""},
RQ_NO3_N:{                                unit:"",  descr:""},
rbCOD_used_by_NO3:{                       unit:"",  descr:""},
rbCOD_available:{                         unit:"",  descr:""},
VFA_rbCOD_ratio:{                         unit:"",  descr:""},
rbCOD_P_ratio:{                           unit:"",  descr:""},
rbCOD_available_normalized:{              unit:"",  descr:""},
P_removal_EBPR:{                          unit:"",  descr:""},
bHT:{                                     unit:"",  descr:""},
bnT:{                                     unit:"",  descr:""},
P_X_bio:{                                 unit:"",  descr:""},
P_removal_synthesis:{                     unit:"",  descr:""},
P_removal_synthesis_n:{                   unit:"",  descr:""},
Effluent_P:{                              unit:"",  descr:""},
P_X_TSS:{                                 unit:"",  descr:""},
P_removal_gday:{                          unit:"",  descr:""},
P_in_waste_sludge:{                       unit:"",  descr:""},
P_removal:{                               unit:"",  descr:""},

//chemP
Fe_III_dose:{                             unit:"",  descr:""},
primary_eff_P:{                           unit:"",  descr:""},
Fe_dose:{                                 unit:"",  descr:""},
percent_Fe_in_FeCl3:{                     unit:"",  descr:""},
amount_FeCl3_solution:{                   unit:"",  descr:""},
FeCl3_volume:{                            unit:"",  descr:""},
storage_req_15_d:{                        unit:"",  descr:""},
Additional_sludge:{                       unit:"",  descr:""},
Fe_dose_M:{                               unit:"",  descr:""},
P_removed:{                               unit:"",  descr:""},
FeH2PO4OH_sludge:{                        unit:"",  descr:""},
Excess_Fe_added:{                         unit:"",  descr:""},
FeOH3_sludge:{                            unit:"",  descr:""},
Excess_sludge:{                           unit:"",  descr:""},
Excess_sludge_kg:{                        unit:"",  descr:""},
Total_excess_sludge:{                     unit:"",  descr:""},
sludge_production_wo_chemical_addition:{  unit:"",  descr:""},
sludge_production_w_chemical_addition:{   unit:"",  descr:""},
Vs_without:{                              unit:"",  descr:""},
Vs:{                                      unit:"",  descr:""},
};
