# column R divided by Q

iso                                                  R/Q
------------------------------------------------------------------
AFG  Afghanistan                                     1
ALB  Albania                                         0.3333333333
DZA  Algeria                                         0.8247280878
ASM  American_Samoa                                  0
AND  Andorra                                         0
AGO  Angola                                          1
AIA  Anguilla                                        1
ATG  Antigua_and_Barbuda                             0
ARG  Argentina                                       0.8661806527
ARM  Armenia                                         1
ABW  Aruba                                           0
AUS  Australia                                       0
AUT  Austria                                         0
AZE  Azerbaijan                                      0.04483823529
BHS  Bahamas                                         0
BHR  Bahrain                                         0
BGD  Bangladesh                                      1
BRB  Barbados                                        0
BLR  Belarus                                         0.1561266667
BEL  Belgium                                         0
BLZ  Belize                                          0.433
BEN  Benin                                           1
BMU  Bermuda                                         0
BTN  Bhutan                                          1
BOL  Bolivia_(Plurinational_State_of)                0.7
BIH  Bosnia_and_Herzegovina                          0.9809111111
BWA  Botswana                                        0
BRA  Brazil                                          0.5696153846
VGB  British_Virgin_Islands                          0
BRN  Brunei_Darussalam                               1
BGR  Bulgaria                                        0.4113587584
BFA  Burkina_Faso                                    1
BDI  Burundi                                         1
CPV  Cabo_Verde                                      1
KHM  Cambodia                                        1
CMR  Cameroon                                        1
CAN  Canada                                          0
BES  Caribbean_Netherlands                           0
CYM  Cayman_Islands                                  1
CAF  Central_African_Republic                        1
TCD  Chad                                            1
CHI  Channel_Islands                                 0
CHL  Chile                                           0.1794656433
CHN  China                                           0.1158181818
HKG  China,_Hong_Kong_Special_Administrative_Region  0.8451245556
MAC  China,_Macao_Special_Administrative_Region      0
COL  Colombia                                        0.8382971354
COM  Comoros                                         1
COG  Congo                                           1
COK  Cook_Islands                                    0
CRI  Costa_Rica                                      0.958
CIV  Côte_d'Ivoire                                   1
HRV  Croatia                                         0.3031088083
CUB  Cuba                                            0.811
CUW  Curaçao                                         0
CYP  Cyprus                                          0
CZE  Czech_Republic                                  0.1330286942
PRK  Democratic_People's_Republic_of_Korea           1
COD  Democratic_Republic_of_the_Congo                1
DNK  Denmark                                         0
DJI  Djibouti                                        1
DMA  Dominica                                        0
DOM  Dominican_Republic                              0.513
ECU  Ecuador                                         0.7125
EGY  Egypt                                           0.2696255176
SLV  El_Salvador                                     1
GNQ  Equatorial_Guinea                               1
ERI  Eritrea                                         1
EST  Estonia                                         0.007917913371
ETH  Ethiopia                                        1
FLK  Falkland_Islands_(Malvinas)                     1
FRO  Faroe_Islands                                   0
FJI  Fiji                                            0
FIN  Finland                                         0
FRA  France                                          0
GUF  French_Guiana                                   0
PYF  French_Polynesia                                0
GAB  Gabon                                           1
GMB  Gambia                                          1
GEO  Georgia                                         0.8998337553
DEU  Germany                                         0.02401479894
GHA  Ghana                                           1
GIB  Gibraltar                                       0
GRC  Greece                                          0
GRL  Greenland                                       0
GRD  Grenada                                         0
GLP  Guadeloupe                                      0
GUM  Guam                                            0
GTM  Guatemala                                       1
GIN  Guinea                                          1
GNB  GuineaBissau                                    1
GUY  Guyana                                          0.5
HTI  Haiti                                           1
VAT  Holy_See                                        0
HND  Honduras                                        0.97
HUN  Hungary                                         0
ISL  Iceland                                         0.2903225806
IND  India                                           0.6281536419
IDN  Indonesia                                       0
IRN  Iran_(Islamic_Republic_of)                      1
IRQ  Iraq                                            0.3280025086
IRL  Ireland                                         0
IMN  Isle_of_Man                                     0
ISR  Israel                                          0.06346915624
ITA  Italy                                           0.0300261481
JAM  Jamaica                                         0.6
JPN  Japan                                           0
JOR  Jordan                                          0
KAZ  Kazakhstan                                      0.198
KEN  Kenya                                           1
KIR  Kiribati                                        1
KWT  Kuwait                                          0
KGZ  Kyrgyzstan                                      1
LAO  Lao_People's_Democratic_Republic                1
LVA  Latvia                                          0.06076249931
LBN  Lebanon                                         0
LSO  Lesotho                                         1
LBR  Liberia                                         1
LBY  Libya                                           0
LIE  Liechtenstein                                   0
LTU  Lithuania                                       0.341956
LUX  Luxembourg                                      0.03138471805
MDG  Madagascar                                      1
MWI  Malawi                                          1
MYS  Malaysia                                        0.039
MDV  Maldives                                        1
MLI  Mali                                            1
MLT  Malta                                           0.06933333333
MHL  Marshall_Islands                                1
MTQ  Martinique                                      0
MRT  Mauritania                                      1
MUS  Mauritius                                       0.6209630859
MYT  Mayotte                                         0
MEX  Mexico                                          0.4923867545
FSM  Micronesia_(Federated_States_of)                0
MCO  Monaco                                          0
MNG  Mongolia                                        1
MNE  Montenegro                                      0.7106666667
MSR  Montserrat                                      0
MAR  Morocco                                         0.5741369487
MOZ  Mozambique                                      1
MMR  Myanmar                                         1
NAM  Namibia                                         1
NRU  Nauru                                           1
NPL  Nepal                                           1
NLD  Netherlands                                     0
NCL  New_Caledonia                                   0
NZL  New_Zealand                                     0
NIC  Nicaragua                                       0.66
NER  Niger                                           0.5
NGA  Nigeria                                         1
NIU  Niue                                            0
MNP  Northern_Mariana_Islands                        0
NOR  Norway                                          0
OMN  Oman                                            0
PAK  Pakistan                                        1
PLW  Palau                                           1
PAN  Panama                                          0.817
PNG  Papua_New_Guinea                                0.436
PRY  Paraguay                                        0.92
PER  Peru                                            0.5794637608
PHL  Philippines                                     1
POL  Poland                                          0
PRT  Portugal                                        0.3114676804
PRI  Puerto_Rico                                     0
QAT  Qatar                                           0
KOR  Republic_of_Korea                               0
MDA  Republic_of_Moldova                             1
REU  Réunion                                         0
ROU  Romania                                         0
RUS  Russian_Federation                              1
RWA  Rwanda                                          0.263
SHN  Saint_Helena                                    0
KNA  Saint_Kitts_and_Nevis                           0
LCA  Saint_Lucia                                     0.54
SPM  Saint_Pierre_and_Miquelon                       0
VCT  Saint_Vincent_and_the_Grenadines                0
WSM  Samoa                                           1
SMR  San_Marino                                      0
STP  Sao_Tome_and_Principe                           1
SAU  Saudi_Arabia                                    0
SEN  Senegal                                         0.5
SRB  Serbia                                          0.9238286786
SYC  Seychelles                                      0
SLE  Sierra_Leone                                    1
SGP  Singapore                                       0
SXM  Sint_Maarten_(Dutch_part)                       0
SVK  Slovakia                                        0.03
SVN  Slovenia                                        0
SLB  Solomon_Islands                                 0
SOM  Somalia                                         0.5
ZAF  South_Africa                                    1
SSD  South_Sudan                                     1
ESP  Spain                                           0.02456071619
LKA  Sri_Lanka                                       1
SDN  Sudan                                           1
SUR  Suriname                                        0.999
SWZ  Swaziland                                       0.497
SWE  Sweden                                          0
CHE  Switzerland                                     0
SYR  Syrian_Arab_Republic                            1
TJK  Tajikistan                                      1
THA  Thailand                                        1
MKD  The_former_Yugoslav_Republic_of_Macedonia       1
TLS  TimorLeste                                      1
TGO  Togo                                            1
TKL  Tokelau                                         0
TON  Tonga                                           0
TTO  Trinidad_and_Tobago                             0
TUN  Tunisia                                         0.03420591318
TUR  Turkey                                          0.51584
TKM  Turkmenistan                                    1
TCA  Turks_and_Caicos_Islands                        0
TUV  Tuvalu                                          1
UGA  Uganda                                          0.5782191781
UKR  Ukraine                                         1
ARE  United_Arab_Emirates                            0.008635653532
GBR  United_Kingdom                                  0.000343997248
TZA  United_Republic_of_Tanzania                     0.2515
VIR  United_States_Virgin_Islands                    0
USA  United_States_of_America                        0.01796765962
URY  Uruguay                                         0.23
UZB  Uzbekistan                                      1
VUT  Vanuatu                                         1
VEN  Venezuela_(Bolivarian_Republic_of)              0.9
VNM  Viet_Nam                                        1
WLF  Wallis_and_Futuna_Islands                       0
PSE  West_Bank_and_Gaza_Strip                        0.2532744543
ESH  Western_Sahara                                  0
YEM  Yemen                                           0.1655519753
ZMB  Zambia                                          1
ZWE  Zimbabwe                                        1

*    Australia_and_New_Zealand                       0
*    Central_Asia_and_Southern_Asia                  0.7034766512
*    Eastern_Asia_and_Southeastern_Asia              0.1468336581
*    Latin_America_and_the_Caribbean                 0.6292639582
*    Northern_America_and_Europe                     0.04891503961
*    Oceania_excluding_Australia_and_New_Zealand     0.5462365295
*    SubSaharan_Africa                               1
*    Western_Asia_and_Northern_Africa                0.4093540734
*    Least_Developed_Countries                       1
*    Landlocked_developing_countries                 0.4283162653
*    Small_island_developing_States                  0.4873039327
*    World                                           0.2732350915
